// <auto-generated />
using System;
using KbrTec.JiuJitsuSystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KbrTec.JiuJitsuSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231031205415_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KbrTec.JiuJitsuSystem.Domain.Entities.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataIncricao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("TipoFaixa")
                        .HasColumnType("int");

                    b.Property<int>("TipoPeso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Atleta", (string)null);
                });

            modelBuilder.Entity("KbrTec.JiuJitsuSystem.Domain.Entities.Campeonato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("date");

                    b.Property<bool?>("EntradaPublico")
                        .HasColumnType("bit");

                    b.Property<int>("FaseCampeonato")
                        .HasColumnType("int");

                    b.Property<string>("Ginasio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InformacoesGerais")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StatusCampeonato")
                        .HasColumnType("int");

                    b.Property<int>("TipoCamepeonato")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Campeonato", (string)null);
                });

            modelBuilder.Entity("KbrTec.JiuJitsuSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("KbrTec.JiuJitsuSystem.Domain.Entities.Campeonato", b =>
                {
                    b.OwnsOne("KbrTec.JiuJitsuSystem.Domain.Entities.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("CampeonatoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Estado");

                            b1.HasKey("CampeonatoId");

                            b1.ToTable("Campeonato");

                            b1.WithOwner()
                                .HasForeignKey("CampeonatoId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
